### ISSUE TITLE
Patching, Dynamic Inventory, and Tasks use case

### ISSUE THREAD

**Issue by hpcprofessional** [puppetlabs-seteam/control-repo#148]
Relative to SKO FY21

Paul Anderson Kevin R. just showed an interesting use case I hadn’t really considered: Using custom facts (in this case patching and change windows) combined with Classification groups to:
Quickly show groups of systems that match whatever fact you’re interested in
Quickly run a task against those groups (e.g. reboot systems pending reboot or patch systems with a given time_window)
This seems to me an interesting use case we should consider highlighting in the new SE Repo, especially as we do more and more with Plans.
But it also shows a cool way to show value in the console relative to OSP. IT is more interesting than just SDLC groups (edited) 

Ryan Russell-Yates Me neither. I hadn't considered a PE Node Group as a set of rules that I'd want nodes to shift in and out from
In this case: Declaring which nodes are patched, which are prepared for patch, etc

**Comment by psreed** [comment]
Closing for now since this is years old. We've adapted this already in our demos anyway. (ie, Creating a dynamic group of `pe_patch.security_patches > 0` and using that for a task run)
