### ISSUE TITLE
role::cloudshop runs with errors on server2012r2a

### ISSUE THREAD

**Issue by mtyates** [puppetlabs-seteam/control-repo#56]
In the vagrant environment, I assign a new/clean server2012r2a node the role::cloudshop, and it runs cleanly, but has the following red errors:  
**Error: Failed to apply catalog: undefined method 'split' for :windows:Symbol**

Oddly, the first run report on the master show as only intentionally changed (though does show the err at the bottom) and subsequent runs show as green check/unchanged.

Subsequent runs in cmd result in the following:
C:\Users\vagrant>puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Facter: error while resolving custom facts in C:/ProgramData/PuppetLabs/p
uppet/cache/lib\facter\cis_windows.rb: undefined method `chomp' for nil:NilClass

Error: Facter: error while resolving custom facts in C:/ProgramData/PuppetLabs/p
uppet/cache/lib/facter\cis_windows.rb: undefined method `chomp' for nil:NilClass

Info: Caching catalog for server2012r2a.pdx.puppet.vm
Info: Applying configuration version 'b3ec01ab0d517a68d1284d60ad0a8c11bfcb260e'
Error: Failed to apply catalog: undefined method `split' for :windows:Symbol

C:\Users\vagrant>

[error-output.txt](https://github.com/puppetlabs-seteam/control-repo/files/1431937/error-output.txt)
[last_run_report.txt](https://github.com/puppetlabs-seteam/control-repo/files/1431953/last_run_report.txt)

**Comment by mtyates** [comment]
Maybe related to this: https://tickets.puppetlabs.com/browse/MODULES-4275
I'm investigating further but wanted to share in case others had a solution.

**Comment by mtyates** [comment]
If it is related to that, then our Puppetfile points to:
mod 'puppetlabs-acl', '1.1.2'
The bug reported in my last update was fixed in a later version of the module:
https://forge.puppet.com/puppetlabs/acl/changelog#2017-05-19---supported-release-200

**Comment by ipcrm** [comment]
Fixed in #55 ; ACL module is bumped to 2.x latest.

@mtyates ^^

**Comment by mtyates** [comment]
Tested and confirmed. The upgrade of the ACL module to the latest fixes the error:
Error: Failed to apply catalog: undefined method 'split' for :windows:Symbol

**Comment by ipcrm** [comment]
#55 has been merged; closing.
