### ISSUE TITLE
profile::platform::baseline fails on server2012r2a - choco errors

### ISSUE THREAD

**Issue by mtyates** [puppetlabs-seteam/control-repo#57]
Applying profile::platform::baseline fails on a fresh server2012r2a with chocolatey errors pointing at the uniextract package.  It appears from this snippet of the error that the hash/checksum didn't match:

"Error - hashes do not match. Actual value was 'D3A1C3D15747EFA884D79CDD997838966C60265D'. ERROR: Checksum for 'C:\Users\vagrant\AppData\Local\Temp\chocolatey\uniextract.install\1.6.1\uniextract.installInstall.exe' did not meet '2e31438e3da025877b3394344d54d7c31c646863' for checksum type 'sha1'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary. The install of uniextract.install was NOT successful. Error while running 'C:\ProgramData\chocolatey\lib\uniextract.install\tools\chocolateyInstall.ps1'. See log for details"

[Chocolatey-error.txt](https://github.com/puppetlabs-seteam/control-repo/files/1438815/Chocolatey-error.txt)
[chocolatey.log](https://github.com/puppetlabs-seteam/control-repo/files/1438816/chocolatey.log)

**Comment by mtyates** [comment]
Odd, I'm able to install manually with choco install and by:
puppet apply -e "package {'uniextract': ensure => installed, provider => chocolatey, }"

I'm going to keep playing around with it.

**Comment by ipcrm** [comment]
@mtyates Is this still a thing?
